---

- name: Ensure superset-web service is defined
  template: src="templates/upstart-web.conf.j2" dest="/etc/init/superset-web.conf" owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  tags: [upstart]
  notify:
    - restart superset-web

- name: Ensure superset-web service state is defined
  service: name=superset-web state="{{ superset_web_state }}" enabled="{{ superset_web_enabled }}"
  notify:
    - restart superset-web
